# Generated by Django 5.1.1 on 2024-10-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
