# Generated by Django 5.1.1 on 2024-10-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rentalhistory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistory',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
