# Generated by Django 5.1.1 on 2024-11-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cars_is_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='acceleration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='drive',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='transmission',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
