# Generated by Django 5.1.1 on 2024-11-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_acceleration_cars_color_cars_drive_cars_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='engine_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
